### ISSUE TITLE
Как ползоваца

### ISSUE THREAD

**Issue by EasyClifton** [TrubaSnorlax/Ekool-marks-calculator#1]
Роскожы как ползоваца а то нехрена не понятно я хочю еколь взломадь

**Comment by ssBandit** [comment]
Тажэ проблема загрузил код а 2 по математике все еще стоит :(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((

**Comment by TrubaSnorlax** [comment]
Очинь жаль что она ни взламивает

**Comment by EasyClifton** [comment]
Нохал пойду сам эколь взламывадь
